server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/db_book_shop
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/book-shop
          jwk-set-uri: http://keycloak:8180/realms/book-shop/protocol/openid-connect/certs
  cloud:
    gcp:
      storage:
        project-id: test-chat-324317
        credentials:
          location: classpath:google-cloud-credentials.json
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: http://kafka-broker:9092

app:
  storage:
    bucket-name: book-shop
    download-public-url: "https://storage-download.googleapis.com"

