server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/db_book_shop
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

