server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/db_book_shop
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  cloud:
    gcp:
      storage:
        project-id: test-chat-324317
        credentials:
          location: classpath:google-cloud-credentials.json

app:
  storage:
    bucket-name: book-shop
    download-public-url: "https://storage-download.googleapis.com"

