version: '3.9'

services:
  db:
    build:
      context: ..
      dockerfile: ./docker-build/db.Dockerfile
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_book_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    networks:
      - web

  book-shop-service:
    build:
      context: ..
      dockerfile: ./docker-build/Dockerfile
    container_name: book-shop-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - web

networks:
  web:
    driver: "bridge"
