version: '3.9'

services:
  db:
    build:
      context: ..
      dockerfile: ./docker-build/db.Dockerfile
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_book_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    networks:
      - web

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    restart: unless-stopped
    command:
      - start --import-realm
    volumes:
      - ./keycloak-config/book-shop-realm.json:/opt/keycloak/data/import/book-shop-realm.json
    environment:
      KC_HTTP_ENABLED: 1
      KC_HOSTNAME_STRICT: 0
      KC_PROXY: edge
      KC_HTTP_PORT: 8180
      KC_HOSTNAME_STRICT_HTTPS: 0
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8180:8180'
    networks:
      - web

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'
    networks:
      - web

  kafka-broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '29092:29092'
    networks:
      - web

  book-shop-service:
    build:
      context: ..
      dockerfile: ./docker-build/Dockerfile
    container_name: book-shop-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db
      - keycloak
      - kafka-broker
    networks:
      - web

networks:
  web:
    driver: "bridge"
